# Generated by Django 2.0.7 on 2018-07-18 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='文章标题')),
                ('js_id', models.CharField(max_length=40, unique=True, verbose_name='简书文章id')),
                ('article_page', models.CharField(max_length=40, verbose_name='简书文章页面')),
                ('newstime', models.DateTimeField(verbose_name='发布时间')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=40, verbose_name='评论内容')),
                ('js_user_id', models.CharField(max_length=40, verbose_name='简书用户id')),
                ('js_article_id', models.CharField(max_length=40, verbose_name='简书文章id')),
                ('js_article_user_id', models.CharField(max_length=40, verbose_name='文章所属用户简书id')),
                ('newstime', models.DateTimeField(verbose_name='评论时间')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('js_user_id', models.CharField(max_length=40, verbose_name='简书用户id')),
                ('js_like_user_id', models.CharField(max_length=40, verbose_name='简书获赞人id')),
                ('js_article_id', models.CharField(max_length=40, verbose_name='简书文章id')),
                ('newstime', models.DateTimeField(verbose_name='点赞时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('js_id', models.CharField(max_length=40, unique=True, verbose_name='简书id')),
                ('home_page', models.CharField(max_length=50, verbose_name='个人主页')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyJianShu.User', verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyJianShu.User', verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyJianShu.User', verbose_name='用户id'),
        ),
    ]
