# Generated by Django 2.0.7 on 2018-07-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyJianShu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=5000, verbose_name='评论内容'),
        ),
    ]
