# Generated by Django 2.0.7 on 2018-07-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyJianShu', '0002_auto_20180718_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=5000, verbose_name='文章标题'),
        ),
    ]
